Chore: 워크플로우 위치 수정

diff --git a/.github/workflows/azure-dev.yml b/.github/workflows/azure-dev.yml
--- a/.github/workflows/azure-dev.yml
+++ b/.github/workflows/azure-dev.yml
@@ -83,12 +83,6 @@ jobs:
           echo "❌ Some tests failed. Deployment will be skipped."
         fi
 
-    - name: ❌ Fail Workflow if Tests Failed on Main Push
-      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.test-status.outputs.tests_passed == 'false'
-      run: |
-        echo "Tests failed on main branch push. Failing the workflow."
-        exit 1
-
     - name: 🔄 Convert Test Results to JUnit Format
       if: github.event_name == 'pull_request'
       run: find ./test-results -name '*.trx' -exec trx2junit {} \;
@@ -106,6 +100,12 @@ jobs:
       with:
         report_paths: '**/test-results/*.xml'
         github_token: ${{ secrets.GITHUB_TOKEN }}
+
+    - name: ❌ Fail Workflow if Tests Failed on Main Push
+      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.test-status.outputs.tests_passed == 'false'
+      run: |
+        echo "Tests failed on main branch push. Failing the workflow."
+        exit 1
 
     - name: 🚀 Log in with Azure (Federated Credentials)
       if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.test-status.outputs.tests_passed == 'true'
